[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#212121"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = ""
gatherUsageStats = false

[runner]
magicEnabled = true

[client]
showErrorDetails = true
